---
name: Run Unit Tests

on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.9
            3.10
            3.11
          cache: 'poetry'

      - name: Poetry Install
        run: poetry install

      - name: Run tox
        run: poetry run tox
